//! `intelnav-registry` binary entry point.

use std::fs;
use std::net::SocketAddr;
use std::path::PathBuf;

use anyhow::{Context, Result};
use clap::{Parser, Subcommand};
use tracing_subscriber::{fmt, prelude::*, EnvFilter};

use intelnav_registry::{gguf, serve, RegistryConfig};

#[derive(Parser, Debug)]
#[command(name = "intelnav-registry", about = "IntelNav shard registry service")]
struct Args {
    #[command(subcommand)]
    cmd: Cmd,
}

#[derive(Subcommand, Debug)]
enum Cmd {
    /// Run the registry HTTP server.
    Serve {
        #[arg(long, default_value = "manifest.toml")]
        manifest: PathBuf,

        #[arg(long, default_value = "0.0.0.0:8787")]
        bind: SocketAddr,

        #[arg(long, default_value_t = 10)]
        reaper_interval_s: u64,
    },

    /// Generate a manifest.toml from a local GGUF file.
    ///
    /// Reads the GGUF header to discover the layer count, computes the
    /// file's sha256 + size, and emits a single-part TOML manifest.
    /// Operators can edit the output to split layer ranges across parts.
    Init {
        /// Path to the GGUF weights file.
        gguf: PathBuf,

        /// URL peers will fetch the weights from.
        /// Defaults to `file://<absolute-path>` for local demos.
        #[arg(long)]
        weight_url: Option<String>,

        /// Content identifier for the model (IPFS CID in prod; any
        /// stable string works for LAN demos).
        #[arg(long)]
        cid: String,

        /// Human-readable model name (e.g. `qwen2.5-0.5b`).
        #[arg(long)]
        name: String,

        /// Quantization tier, as recorded in the model registry.
        #[arg(long, default_value = "Q4_K_M")]
        quant: String,

        /// Write to this path instead of stdout.
        #[arg(long, short = 'o')]
        output: Option<PathBuf>,
    },
}

#[tokio::main]
async fn main() -> Result<()> {
    tracing_subscriber::registry()
        .with(EnvFilter::try_from_default_env().unwrap_or_else(|_| EnvFilter::new("info")))
        .with(fmt::layer().compact())
        .init();

    let args = Args::parse();
    match args.cmd {
        Cmd::Serve { manifest, bind, reaper_interval_s } => {
            serve(RegistryConfig { bind, manifest_path: manifest, reaper_interval_s }).await
        }
        Cmd::Init { gguf: gguf_path, weight_url, cid, name, quant, output } => {
            cmd_init(gguf_path, weight_url, cid, name, quant, output)
        }
    }
}

fn cmd_init(
    gguf_path: PathBuf,
    weight_url: Option<String>,
    cid: String,
    name: String,
    quant: String,
    output: Option<PathBuf>,
) -> Result<()> {
    let abs = gguf_path.canonicalize()
        .with_context(|| format!("resolving {}", gguf_path.display()))?;

    let info = gguf::read_info(&abs)
        .with_context(|| format!("parsing gguf {}", abs.display()))?;
    let size_bytes = fs::metadata(&abs)
        .with_context(|| format!("statting {}", abs.display()))?
        .len();
    let sha = gguf::sha256_hex(&abs)
        .with_context(|| format!("hashing {}", abs.display()))?;

    let url = weight_url.unwrap_or_else(|| format!("file://{}", abs.display()));
    let total = info.block_count;

    let toml = format!(
        "# generated by `intelnav-registry init`\n\
         # arch={arch}  file={file}\n\
         \n\
         [model]\n\
         cid          = \"{cid}\"\n\
         name         = \"{name}\"\n\
         quant        = \"{quant}\"\n\
         total_layers = {total}\n\
         \n\
         [defaults]\n\
         desired_k                = 1\n\
         heartbeat_interval_s     = 20\n\
         heartbeat_miss_tolerance = 3\n\
         min_live_seconds         = 30\n\
         reservation_ttl_s        = 300\n\
         replay_window_s          = 120\n\
         assign_rate_per_hour     = 6\n\
         \n\
         [[part]]\n\
         id             = \"p1\"\n\
         layer_range    = [0, {last}]\n\
         weight_url     = \"{url}\"\n\
         sha256         = \"{sha}\"\n\
         size_bytes     = {size_bytes}\n\
         min_vram_bytes = 0\n",
        arch = info.architecture,
        file = abs.display(),
        last = total.saturating_sub(1),
    );

    match output {
        Some(path) => {
            fs::write(&path, &toml)
                .with_context(|| format!("writing {}", path.display()))?;
            eprintln!("wrote {} ({} bytes)", path.display(), toml.len());
        }
        None => print!("{toml}"),
    }
    Ok(())
}
